version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: abhushan
    volumes:
      - ./setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
  app:
    image: abhushan-jewellers
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 13000:3000
    depends_on:
      - db